kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: openjre18-171
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'openjre18-171:1.0'
  resources: {}
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel7-atomic:7.4-131'
      pullSecret:
        name: redhat-registry
  postCommit: {}
  source:
    type: Binary
    binary: {}
    ##---------------------------------------
    ## This section is NOT required if you are using the MachineConfg,
    ## uncomment for the "Testing" section to leverage ConfigMaps & Secrets.
    ##
    # configMaps:
    # - configMap:
    #     name: rhsm-conf
    #   destinationDir: rhsm-conf
    # - configMap:
    #     name: rhsm-ca
    #   destinationDir: rhsm-ca
    # secrets:
    # - secret:
    #     name: etc-pki-entitlement
    #   destinationDir: etc-pki-entitlement
    ##---------------------------------------
  triggers: []
  runPolicy: Serial
status:
